---
abstract: Apply code to each array element and a block of successors
author:
  - 'Bjoern Hoehrmann <bjoern@hoehrmann.de>'
build_requires: {}
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: List-EachCons
no_index:
  directory:
    - t
    - inc
resources:
  repository: https://github.com/hoehrmann/List-EachCons.git
version: 0.01
